### PR TITLE
Update tsconfig.json

### PR DESCRIPTION
**Pull request by gprzybylowicz**
Switch to emitting ES2015 to account for Typedoc emitting ES2015

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Is this the fix for TypeDoc 0.14?

**Comment by birkir** [comment]
Yes! 👍

**Comment by HazAT** [comment]
We need this fix please :) 
Without it we get
```
Error: The plugin /Users/haza/Projects/sentry-javascript/node_modules/typedoc-plugin-monorepo could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new ExternalModuleMapPlugin (/Users/haza/Projects/sentry-javascript/node_modules/typedoc-plugin-monorepo/plugin.js:67:46)
    at Converter.addComponent (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/utils/component.js:123:19)
    at Converter.addComponent (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/converter/converter.js:28:33)
    at module.exports (/Users/haza/Projects/sentry-javascript/node_modules/typedoc-plugin-monorepo/index.js:8:17)
    at PluginHost.load (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/utils/plugins.js:36:21)
    at CliApplication.bootstrap (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/application.js:42:22)
    at CliApplication.bootstrap (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/cli.js:24:30)
    at new Application (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/application.js:31:14)
    at new CliApplication (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/dist/lib/cli.js:22:1)
    at Object.<anonymous> (/Users/haza/Projects/sentry-javascript/node_modules/typedoc/bin/typedoc:4:1)
```

**Comment by unstubbable** [comment]
@HazAT Take a look at [@strictsoftware/typedoc-plugin-monorepo](https://www.npmjs.com/package/@strictsoftware/typedoc-plugin-monorepo). It's a fork of `typedoc-plugin-monorepo` that includes a fix for this issue (based on @gprzybylowicz's fork), fixes [another issue regarding the lookup of READMEs](https://github.com/unstubbable/typedoc-plugin-monorepo/commit/fce878df4e2fd46e154df1498c25f704ba4ee9ea), and also includes a replacement of Typedoc's built-in `TocPlugin`, which lists the monorepo modules as top-level entries in the table of contents. — [Example API Docs](https://feature-hub.io/@feature-hub/)

**Comment by HazAT** [comment]
@unstubbable Woohoo, awesome thanks, will use your fork from now on. 💯 
https://github.com/getsentry/sentry-javascript/commit/f1a844b14b0f39dc6a790163079d806f6ac034c1

**Comment by ghost** [comment]
@unstubbable  your version has also some issue 
```
Loaded plugin /Users/kishan/tavisca/orxe-core-sdk/node_modules/@strictsoftware/typedoc-plugin-monorepo

Using TypeScript 3.7.5 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
/Users/kishan/tavisca/orxe-core-sdk/node_modules/@strictsoftware/typedoc-plugin-monorepo/dist/external-module-map-plugin.js:64
            this.options.read({}, options_1.OptionsReadMode.Prefetch);
                                                            ^

TypeError: Cannot read property 'Prefetch' of undefined
    at ExternalModuleMapPlugin.onBegin (/Users/kishan/tavisca/orxe-core-sdk/node_modules/@strictsoftware/typedoc-plugin-monorepo/dist/external-module-map-plugin.js:64:61)
    at triggerEvents (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:128:43)
    at triggerApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:110:13)
    at eventsApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:21:18)
    at Converter.trigger (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:264:13)
    at Converter.convert (/usr/local/lib/node_modules/typedoc/dist/lib/converter/converter.js:89:14)
    at CliApplication.convert (/usr/local/lib/node_modules/typedoc/dist/lib/application.js:72:39)
    at CliApplication.bootstrap (/usr/local/lib/node_modules/typedoc/dist/lib/cli.js:45:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/typedoc/bin/typedoc:5:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by maneetgoyal** [comment]
@unstubbable The above error was recently fixed in [asgerjensen/typedoc-plugin-external-module-map](https://github.com/asgerjensen/typedoc-plugin-external-module-map). Could you please sync `@strictsoftware/typedoc-plugin-monorepo`? I am using `@strictsoftware/typedoc-plugin-monorepo` and can't update TypeDoc because of this error. Many thanks for the useful plugin.

---

Here's the fix by @danbalarin: https://github.com/asgerjensen/typedoc-plugin-external-module-map/pull/9

**Comment by unstubbable** [comment]
📦 Published as [@strictsoftware/typedoc-plugin-monorepo@0.3.0](https://www.npmjs.com/package/@strictsoftware/typedoc-plugin-monorepo/v/0.3.0)

On a related note, I enabled [issues for my forked repo](https://github.com/unstubbable/typedoc-plugin-monorepo/issues). In the future, feel free to report bugs like this there.

**Comment by amiller-gh** [comment]
Thanks @unstubbable for taking ownership here! 🙁 Sorry for missing this activity on this thread! (The Node.js Github org notification firehose was on full force at that time I believe).

Will modify the README pointing folks to @strictsoftware/typedoct-plugin-monorepo as source of truth from now on, since I've moved on from the project using this library, that will be a better home for this from now on 🙏

**Pull request merged**
